name: Testing Second Action
on: 
    workflow_dispatch:
        inputs:
            node-version:
                description: "Choose node version"
                required: false
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x
jobs:
    test:
        environment: development
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v5
              with:
                node-version: '${{github.event.inputs.node-version}}'
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test
    deploy:
        environment: Development
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v5
            - name: Install NodeJS
              uses: actions/setup-node@v5
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Build project
              run: npm run build
            - name: Deploying
              run: |
                echo "${{env.AWS_SECRET_KEY}}"
